### ISSUE TITLE
Remove test deps from „install_requires”

### ISSUE THREAD

**Issue by ionelmc** [epsy/clize#22]
One thing that annoys me a lil bit is that install_requires has various deps that are only needed for testing.

Perhaps clize could move them to tests_require or install them specifically just for CI? What are your thoughts on this?

**Comment by epsy** [comment]
It's a good idea.

It doesn't look like tox installs the 'test_requires' dependencies. There doesn't seem to be an imminent fix for this: tox-dev/tox#13

Given that it seems some downstream CIs prefer to use setuptools' test command (e.g. [1](https://github.com/NixOS/nixpkgs/pull/14845/commits/21f6437365a16f57ba221ef2b24c8511b7293284) -> [2](https://github.com/NixOS/nixpkgs/blob/a2c867fd394306bf28804696eef67c9bb7ffbbcb/pkgs/development/interpreters/python/build-python-package-setuptools.nix#L35)) it seems preferable to have both test_requires and tox dependencies.
