### ISSUE TITLE
clize.converters.file always uses default value

### ISSUE THREAD

**Issue by kouk** [epsy/clize#29]
The following code doesn't work as expected when a value is provided:
```
from clize import run
from clize.converters import file

def write_config(*args, output: file(mode='w')='-'):
    """Write out a sample config file.

    :param output: the path to the file to write.
    """
    with output as fp:
        fp.write("hi!\n")

if __name__ == '__main__':
    run(write_config)
```
What I expected was the default would be not be used, but in this case it is always used even if I pass a parameter. For example:
```
$ python test.py --output=/tmp/test
hi!
```

AFAICS changes made to `clize.parser.CliBoundArguments` in https://github.com/epsy/clize/commit/c2b5b85e5e07ee6a38df0839def5c3a3b4b3abb2 have created the problem.

**Comment by epsy** [comment]
Closed fixed.
