### ISSUE TITLE
[Question] Changing variable from command line

### ISSUE THREAD

**Issue by Kristinita** [epsy/clize#33]
### 1. Briefly

I don't understand, how I can change one variable from command line.

#### 1. Environment

+ Windows 10 64-bit Enterprise EN,
+ Python 3.6.3,
+ Clize 4.0.2.

#### 2. File

For example, I have a file, where I use [**Logbook**](https://logbook.readthedocs.io/en/stable/) logging.

```python
import logbook
import sys

logbook.StreamHandler(sys.stdout,
                        level=logbook.WARNING).push_application()
log = logbook.Logger("Sasha Logbook")

log.debug("Debug message")
log.warning("Warning message")
log.error("Error message")
```

**If** I run this file in console, I get output:

```shell
D:\SashaPythonista>python SashaLogbook.py
[2018-01-01 17:55:47.063625] WARNING: Sasha Logbook: Warning message
[2018-01-01 17:55:47.064624] ERROR: Sasha Logbook: Error message
```

Output, **if** `logbook.StreamHandler(sys.stdout, level=logbook.DEBUG).push_application()`:

```shell
[2018-01-01 17:55:46.994054] DEBUG: Sasha Logbook: Debug message
[2018-01-01 17:57:26.982679] WARNING: Sasha Logbook: Warning message
[2018-01-01 17:57:26.983677] ERROR: Sasha Logbook: Error message
```

And so on.

### 2. Expected behavior

**If**:

```shell
D:\SashaPythonista>python SashaLogbook.py level=DEBUG
[2018-01-01 17:55:46.994054] DEBUG: Sasha Logbook: Debug message
[2018-01-01 17:55:47.063625] WARNING: Sasha Logbook: Warning message
[2018-01-01 17:55:47.064624] ERROR: Sasha Logbook: Error message
```

**If**:

```shell
D:\SashaPythonista>python SashaLogbook.py level=WARNING
[2018-01-01 17:57:26.982679] WARNING: Sasha Logbook: Warning message
[2018-01-01 17:57:26.983677] ERROR: Sasha Logbook: Error message
```

And so on.

### 3. Actual behavior

I try to add Clize:

```python
import logbook
import sys

from clize import run

log = logbook.Logger("Sasha Logbook")


def test(level="WARNING"):

    if level == "DEBUG":
        logbook.StreamHandler(sys.stdout,
                              level=logbook.DEBUG).push_application()
    if level == "WARNING":
        logbook.StreamHandler(sys.stdout,
                              level=logbook.WARNING).push_application()
    if level == "ERROR":
        logbook.StreamHandler(sys.stdout,
                              level=logbook.ERROR).push_application()


run(test)

log.debug("Debug message")
log.warning("Warning message")
log.error("Error message")

```

**If** I replace `run(test)` to `test()`, Logbook messages print to console. But if I use `run(test)`, I haven't output in console.

```shell
D:\SashaPythonista>python SashaLogbook.py --help
Usage: SashaLogbook.py [level]

Arguments:
  level         (default: WARNING)

Other actions:
  -h, --help   Show the help

D:\SashaPythonista>python SashaLogbook.py level=DEBUG

D:\SashaPythonista>python SashaLogbook.py level=ERROR
```

### 4. Did not help

1. I see [**example**](https://github.com/epsy/clize/blob/master/examples/logparam.py) for logging, but it hard for me. I want only control logging levels from command line.

### 5. Do not offer

1. I want to use Logbook, not default Python logging module.

Thanks.

**Comment by edk0** [comment]
You need to specify arguments like `--level=whatever` (or extend the
parser, but using the standard format seems like a good idea)

**Comment by Kristinita** [comment]
@edk0 ,

> You need to specify arguments like `--level=whatever` (or extend the parser, but using the standard format seems like a good idea)

I'm sorry, where, in what place I need to specify arguments? Can you show simple example?

Thanks.

**Comment by edk0** [comment]
`python SashaLogbook.py --level=DEBUG`

**Comment by Kristinita** [comment]
```shell
D:\SashaPythonista>python SashaLogbook.py --level=DEBUG
SashaLogbook.py: Unknown option '--level'. Did you mean '--help'?
Usage: SashaLogbook.py [level]
```

**Comment by epsy** [comment]
When you write `def test(level="WARNING"):`, you get what Clize (and python) calls an optional positional argument. This means you can give it a value just on its own, like this:

    $ python SashaLogbook.py ERROR

When you write `python SashaLogbook.py level=ERROR` your program receives `"level=ERROR"`. None if your `if`s detect it so your program doesn't create a log output. I suggest changing your `if`s to a chain of `if-elif-elif-else`, with an `else` that gives you an error message and exits. That way you can detect if the input is not exactly what you epected.

Now, if you want to be able to write this instead:

    $ python SashaLogbook.py --level=ERROR

Then you need an option parameter:

    def test(*, level="WARNING"):
        ...

It is documented here: http://clize.readthedocs.io/en/stable/basics.html#accepting-options (The page also links to how you can do this on Python 2 -- feel free to ask for details on this too)

**Comment by Kristinita** [comment]
All right, I understand, how worked simple example:

```python
from clize import run


def echo(*, prefix='f'):
    """Echoes prefix parameter

    :param prefix: Print specified letter
    """
    print(prefix)


run(echo)

```

Output:

```shell
D:\SashaPythonista>python SashaClize.py --prefix=Example
Example
```

But what should I do next? What else should I read in order to perform my task?

Thanks.

**Comment by epsy** [comment]
Ah, I just spotted another problem:

In your `3.` example, you use `run(test)` and then print the log messages. By default, `run()` exits the program with an appropriate exit code. You have to either move the `log.X("...")` calls into `def test`, or you can tell Clize not to exit: `run(test, exit=False)`

**Comment by Kristinita** [comment]
@epsy , thank you!

Working example:

```python
import logbook
import sys

log = logbook.Logger("Sasha Logbook")


def clize_log_level(*, logbook_level: 'll'="WARNING"):
    """Change log levels via command line.

    User select, which logging messages to see. See about 6 log levels here:
    https://logbook.readthedocs.io/en/stable/quickstart.html

    :param logbook_level: user select logging level
    """

     if logbook_level == "DEBUG":
         logbook.StreamHandler(sys.stdout,
                               level=logbook.DEBUG).push_application()
     if logbook_level == "WARNING":
         logbook.StreamHandler(sys.stdout,
                               level=logbook.WARNING).push_application()
     if logbook_level == "ERROR":
            logbook.StreamHandler(sys.stdout,
                                  level=logbook.ERROR).push_application()

run(clize_log_level, exit=False)

log.debug("Debug message")
log.warning("Warning message")
log.error("Error message")

```
