### ISSUE TITLE
Case-sensitive 1-character aliases are not allowed

### ISSUE THREAD

**Issue by richieadler** [epsy/clize#39]
This code in 1.py:

```
import clize

def main(*, update:'U'=False, uranus:'u'=False):
    pass

if __name__ == '__main__':
    clize.run(main)

```

produces this result:

```
> 1.py -h

ValueError: parameters '--update' and '--uranus' use a duplicate alias '-u'
```

In previous versions this worked.

Tested in Windows 7, Python 3.6.2, clize 4.0.3

**Comment by epsy** [comment]
Thanks for the bug report. I've fixed the issue and will have it in a release soon.

**Comment by richieadler** [comment]
Any chance of having a new release soon?
