### ISSUE TITLE
Any issue with `attrs>=20.0.0`?

### ISSUE THREAD

**Issue by arthur-rtzr** [epsy/clize#62]
I'm using clize with attrs>=20.3.0. requirements are currently conflict between clize and attrs.

Any plan for update `attrs>=19.1.0,<20` to `attrs>=19.1.0,<21`?

**Comment by nodakai** [comment]
@epsy Is it possible to make a "pre-release" such as`clize 4.2a0` with `attrs>=19.1.0,<21` (or even, just `attrs>=19.1.0`) on a provisional basis?

https://www.python.org/dev/peps/pep-0440/#pre-releases
https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

For example, [Airflow](https://airflow.apache.org/) requires `attrs >= 20` for whatever reasons, and we are having a difficulty in maintaining `clize`-based scripts to work with it.

Actually the main motivation behind my pending PR #61 was to make this happen in a safer manner... but I haven't got time to teach myself with `coveralls`, haven't made any progress yet.

**Comment by epsy** [comment]
clize should now be installable alongside attrs 19 through 21
