### ISSUE TITLE
repeated_test no longer compatible with 3.10

### ISSUE THREAD

**Issue by jonringer** [epsy/clize#74]
`repeated_test` relies on `unittest2`, which is longer compatible with python 3.10.

Both packages haven't been maintained in 5 years.

They should be dropped.

related: https://github.com/epsy/sigtools/issues/26

**Comment by epsy** [comment]
As in epsy/sigtools#26 few other incompatibilities affect supporting 3.10 across clize/sigtools just yet. I'll make sure `repeated_test` is also updated in the process.

Thanks for bringing it up!

**Comment by epsy** [comment]
Fixed with `repeated_test 2.3.1`, `clize 5.0.0`
